# Generated by Django 3.2.8 on 2021-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20211019_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='max_student',
            field=models.IntegerField(default=20),
        ),
    ]
